name: build workflow

on:
  release:
    types: [published]
jobs:
  release:
      name: Release on GitHub
      runs-on: ubuntu-latest
      steps:
        - name: Check out code
          uses: actions/checkout@v1
        - name: Validates GO releaser config
          uses: docker://goreleaser/goreleaser:latest
          with:
            args: check
        - name: Create release on GitHub
          uses: docker://goreleaser/goreleaser:latest
          with:
            args: release
          env:
            GITHUB_TOKEN: ${{secrets.TOKEN}}

  build:
      runs-on: ubuntu-latest
      name: Build image job
      steps:
        - name: Checkout master
          uses: actions/checkout@master
        - name: Docker Login
          # You may pin to the exact commit or the version.
          # uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
          uses: docker/login-action@v1.10.0
          with:
            # Username used to log against the Docker registry
            username: ${{ secrets.DOCKER_USERNAME }} # optional
            # Password or personal access token used to log against the Docker registry
            password: ${{ secrets.DOCKER_PASSWD }} # optional
            # Log out from the Docker registry at the end of a job
            logout: true # optional, default is true
        - name: Extract metadata (tags, labels) for Docker
          id: meta
          uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
          with:
            images: kalifun/shiori
          
        - name: Build and push Docker images
          uses: docker/build-push-action@v2.7.0
          with:
            context: .
            push: true
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}